- name: Activate the Python virtual environment with pyenv and install Playwright
  shell: source {{ virtual_env_path }}/bin/activate && playwright install
  environment:
    VIRTUAL_ENV: "{{ virtual_env_path }}"
  args:
    executable: /bin/bash

- name: Copy .env file.
  template:
    src: env.j2
    dest: "{{ project_path }}/.env"


- name: Run Migrations
  shell:
    chdir: "{{ project_path }}"
    cmd: "{{ virtual_env_path }}/bin/python manage.py makemigrations --noinput"


- name: migrate
  shell:
    chdir: "{{ project_path }}"
    cmd: "{{ virtual_env_path }}/bin/python manage.py migrate --noinput"


# - name: Start Celery 
#   shell: 
#     cmd: "celery --app=LabelWebApp.celery worker --loglevel=info --concurrency 4"



# - name: Create a systemd service unit file for the Django application
#   template:
#     src: django.service.j2
#     dest: /etc/systemd/system/django.service
#   notify:
#     - Reload systemd

# - name: Ensure Django service is enabled and started 
#   systemd:
#     name: django
#     state: started
#     enabled: yes
